### PR TITLE
RTL support for html2canvas

### PR DESCRIPTION
**Pull request by nicholasgonzalezsc**
This PR is based off of the solution found here https://github.com/niklasvh/html2canvas/issues/686#issuecomment-163111339

Also related: https://github.com/niklasvh/html2canvas/issues/948

### CODE REVIEW

**Comment by niklasvh** [comment]
Thanks for the PR! I'll need some time to look through and get a better understanding of RTL in general, as I am not very familiar of how it works, how https://developer.mozilla.org/en-US/docs/Web/CSS/direction impacts it, as well as https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/dir

**Comment by webtinax** [comment]
hi please fix this problem and add to html2canvas

**Comment by idolizesc** [comment]
@niklasvh Do you think you'll get a chance to look at this and integrate it?

**Comment by Mignon-han** [comment]
I am very concerned about when this problem can be solved.

**Comment by kinging123** [comment]
@niklasvh any news about this? 😢

**Comment by mohafouad** [comment]
any updates :(

**Comment by Avishaidev** [comment]
any updates?

**Comment by IDSELAADMCODE** [comment]
Any updates on letters splitting?

**Comment by ghonchesefidi** [comment]
Any update?

**Review by hasanparasteh — CHANGES_REQUESTED** [review]
Please consider adding Persian/Farsi in your `SUPPORTED_RTL_CATEGORIES` list

**Comment by chaim-chv** [comment]
any updates?
current version doesn't support RTL languages.. this is so disappointing 🤕

**Comment by niklasvh** [comment]
RTL support added in https://github.com/niklasvh/html2canvas/pull/2653

**Comment by ghonchesefidi** [comment]
@niklasvh Thanks for your effor. Good job.

**Pull request closed without merging**
