### PR TITLE
Add 'dist' directory to git to allow get main file with bower

### LINKED ISSUE #710: Can't get main file with bower (dist/html2canvas.js)
This happens because 'dist' directory was excluded from git

### PR DESCRIPTION
**Pull request by driver-by**
Resolves #710
The 'dist' was removed for some purposes. So I don't know if my method is suitable.
But now it's impossible to get dist file with bower (for v0.5)

### CODE REVIEW

**Comment by cbrady1** [comment]
Package is unusable with the 'dist' directory. Can this PR get merged?

**Comment by akovalyov** [comment]
Personally I am not sure about that dist files should be kept in git tree. IMO better to generate them during the release cycle.

**Comment by driver-by** [comment]
It's impossible to use this project with bower now. Dists should be included either in this repository, or some another with just dists file for bower.
I've seen many js repos and don't remember any without main files.

**Comment by cbrady1** [comment]
@akovalyov Ok, then please explain how am I to incorporate your library into my project using bower?

**Comment by akovalyov** [comment]
@cbrady1 I'd really like to help you, but I am neither author nor maintainer of this lib, so I can't help you. It is something @niklasvh should change during his release cycle. Everything I can do for you is just to publish a gist with compiled source. Here you go - [html2canvas.js](https://gist.github.com/akovalyov/f820ff33bf160b291d64), [html2canvas.svg.js](https://gist.github.com/akovalyov/51d220c907bd7398bca9), [html2canvas.min.js](https://gist.github.com/akovalyov/dde3a8d9bfc28c7511cb) and [html2canvas.svg.min.js](https://gist.github.com/akovalyov/53b51038ce93baa697b8)

**Comment by cbrady1** [comment]
Oops sorry for some reason I thought it was you!

Sent from my iPhone


[cid:sme-pme-2014-english03496d]<http://www.eluta.ca/jobs-at-longbow-advantage>      [cid:sme-pme-2014-francais518743] <http://www.eluta.ca/jobs-at-longbow-advantage>

On Nov 25, 2015, at 4:30 PM, Andrew Kovalyov <notifications@github.com<mailto:notifications@github.com>> wrote:


@cbrady1<https://github.com/cbrady1> I'd really like to help you, but I am neither author nor maintainer of this lib, so I can't help you. It is something @niklasvh<https://github.com/niklasvh> should change during his release cycle. Everything I can do for you is just to publish a gist with compiled source. Here you go - html2canvas.js<https://gist.github.com/akovalyov/f820ff33bf160b291d64>, html2canvas.svg.js<https://gist.github.com/akovalyov/51d220c907bd7398bca9>, html2canvas.min.js<https://gist.github.com/akovalyov/dde3a8d9bfc28c7511cb> and html2canvas.svg.min.js<https://gist.github.com/akovalyov/53b51038ce93baa697b8>

**Comment by akovalyov** [comment]
@cbrady1. no worries, at least there are some dist files resusable :)

**Comment by niklasvh** [comment]
Re-added them for now https://github.com/niklasvh/html2canvas/commit/47a7240d6b0c804b0783ed41469abdc313ce0139

**Pull request closed without merging**
