### PR TITLE
Scale foreignObject image to fill the canvas

### PR DESCRIPTION
**Pull request by eKoopmans**
Fix scaling on foreignObject rendering.

### CODE REVIEW

**Comment by niklasvh** [comment]
This change breaks all the tests under tests/reftests/options. The scaling should already be correct as the SVG image is created with the scaling (https://github.com/niklasvh/html2canvas/blob/master/src/renderer/ForeignObjectRenderer.js#L24-L27). Do you have an example where it isn't working correctly?

**Comment by eKoopmans** [comment]
Hmm interesting, it's scaled wrong for me. Yeah, I'll make a fiddle if you can help out with the external resource.

**Comment by eKoopmans** [comment]
[Fiddle](https://jsfiddle.net/0k4o7vks/1/). Tested in Chrome (FF, IE, and Edge all fall back to canvas rendering instead of foreignObject). The entire div is half its intended width in the canvas on my machine.

**Comment by niklasvh** [comment]
Yep, seeing same results as you. Need to figure out what is breaking the tests vs. what is breaking this.

**Pull request closed without merging**
