### PR TITLE
Fixed loading images from blobs

### LINKED ISSUE #1908: Image blob isn't captured
- [ X ] You are using the latest [version](https://github.com/niklasvh/html2canvas/releases)
- [ X ] You are testing using the non-minified version of html2canvas and checked any potential issues reported in the console

I'm upgrading a project from a very old version (0.4) to the current version, and now have issues with html2canvas converting a CORS image. The canvas size is correct, but the canvas itself is blank.

The image source is a blob, such as 

``

The below code works in codepen with a standard image url source, but doesn't work in my project with the blob source. I'm not sure how to provide an example since the URL the blob is returned from is only available on an intranet.

```
html2canvas($(htmlDiv).get(0), {
            allowTaint: true,
            taintTest: false,
            useCORS: true,
            scale: 1
        }).then(function(canvas) {

            console.log("html2canvas conversion :: " + htmlDiv + " converted successfully");

            
            $('#html-wrapper').append(canvas);
        });
```

There are no issues in the console.

### Specifications:

 * html2canvas version tested with: 1.0.0-rc2 and 1.0.0-rc3
 * Browser & version: IE 11

### PR DESCRIPTION
**Pull request by vsevolodp**
**Summary**

Fixed loading images with src like "blob:..."

This PR fixes/implements the following **bugs/features**

* [1908] Bug 1

**Closing issues**

Fixes #1908

### CODE REVIEW

**Comment by abshakekumar** [comment]
When we can expect this PR to be merged ?

**Comment by chloeavoustin** [comment]
As already requested, are there any plans to merge this? I need it for a project.

**Comment by cuongqle** [comment]
i got same issue with latest version 1.0.0-rc5
Does this fix get merge to latest version?

**Comment by Shavindra** [comment]
This is not released yet?

**Comment by zfha** [comment]
when to release it?

**Comment by snehalatasahu** [comment]
Still, getting "Error loading image blob: ..." how should I fix it?

**Pull request closed without merging**
