### PR TITLE
Fix #541

### LINKED ISSUE #541: Text tags in SVG overlap (duplicated / doubling)
(Sorry, I am not good at english)

Hello,
I am using this awesome script to render SVG tags
There is some text overlapping when I render the text tag in SVG to canvas
Text tag be processed as a Text node and also SVG
You can see that easily with transform property

Here is sample code (with html2canvas 0.5.0-alpha2)

```
<html>
<head>
  <script src="https://code.jquery.com/jquery-1.11.2.min.js"></script>
  <script type="text/javascript" src="js/html2canvas.js"></script>
</head>
<body>
  <svg width="100" height="100">
    <g transform="translate(20,20)">
      <text dy=".45em" y="10" x="0" dx="-.8em" transform="translate(0,0) rotate(-70)" style="font-size:12px;">Text</text>
    </g>
  </svg>
  <script>
    $(document).ready(function() {
      html2canvas(document.body, {
        onrendered: function(canvas) {
          document.body.appendChild(canvas);
        }
      });
    })
  </script>
</body>
</html
```

And Here is my quick change

```
NodeParser.prototype.getChildren = function(parentContainer) {
    return flatten([].filter.call(parentContainer.node.childNodes, renderableNode).map(function(node) {
        var container = [node.nodeType === Node.TEXT_NODE && node.parentElement.tagName !== "text" ? new TextContainer(node, parentContainer) : new NodeContainer(node, parentContainer)].filter(nonIgnoredElement);
        return node.nodeType === Node.ELEMENT_NODE && container.length && node.tagName !== "TEXTAREA" ? (container[0].isElementVisible() ? container.concat(this.getChildren(container[0])) : []) : container;
    }, this));
};
```

I hope this will help

### PR DESCRIPTION
**Pull request by hyojin**
SVG Text node is processed as NodeContainer instead of TextContainer.

### CODE REVIEW

**Comment by ncoquelet** [comment]
you can change your description to :

SVG Text node must be processed as NodeContainer instead of TextContainer.

**Comment by niklasvh** [comment]
Fixed in 1.0.0

**Comment by GoodJeans** [comment]
I am still facing this issue, when I use padding or margin, there is duplicated text I posted, I realised the problem is resolved when I remove my padding and margin. However I need my padding and margin to make the text in line with the graph is there anyway to fix this?
The code below will display duplicate text.

 <svg width="170" height="350" style="margin-top: 50px;border: 0px solid black;">
                        <rect x="10" y="150" width="20" height="20" fill="#19A594" />
                        <rect x="10" y="200" width="20" height="20" fill="#FFCC66" />
                        <rect x="10" y="250" width="20" height="20" fill="#134F4D" style="fill-opacity:0.5;" />
                        
                          <text x="35" y="165">
                          <tspan font-weight="bold" fill="blue">OA: </tspan>
                          <tspan >$50,000.00</tspan> 
                        </text>
                          <text x="35" y="215">
                          <tspan font-weight="bold" fill="blue">SA: </tspan>
                          <tspan >$150,000.00</tspan> 
                        </text>
                          <text x="35" y="265" style="fill-opacity:0.5;">
                          <tspan font-weight="bold" fill="blue">MA: </tspan>
                          <tspan >$40,000.00</tspan> 
                        </text>
                    </svg>
https://github.com/eKoopmans/html2pdf/issues/75

**Comment by dydokamil** [comment]
@GoodJeans do you mean the margin/padding around the whole chart or just the text? I don't have any spacing around my text, but I must keep it around the entire chart. No idea how to fix it.

**Comment by Revavthisreddyb** [comment]
@hyojin, this solution is not working for IE11?? Coz, i do not see any SVG getting displayed on IE.

**Pull request closed without merging**
