### PR TITLE
Fix rendering of offscreen elements

### PR DESCRIPTION
**Pull request by eKoopmans**
## Bug: Off-screen rendering

Off-screen components are currently not being rendered.

bugfix-offscreen

### Fix

When the `type: 'view'` option is not set, the width of the renderer is set to the `right` and `bottom` bounds of the root node, rather than the document width/height.

### Related issues/pull requests

#117, #461, #590, #622, #774, #836, #837, #876

### CODE REVIEW

**Comment by Romerski** [comment]
@eKoopmans Hi. I tryed your fix but im not able to make this work. I have this: http://i.imgur.com/EE8GyHD.png

Green: Popup when I click print button on Gantt chart.
Blue: HTML gantt chart which I want to render.
Red: What is rendering html2canvas from html (only screen visible part of html)

Is a gantt chart rendered by JQuery.gantt, any help to fix this? Thanks!!

**Comment by eKoopmans** [comment]
Sure @Romerski, I'll take a look. Can you give me a link to your page where you're generating the canvas, or a similar demo?

**Comment by Romerski** [comment]
@eKoopmans Sure, I'll send you an email to erik@erik-koopmans.com with webpage and login user. 
Thanks!!

**Comment by Romerski** [comment]
@eKoopmans Sure! I've sent you an email to erik@erik-koopmans.com. Thank again!

**Comment by eKoopmans** [comment]
@Romerski, I've had a look. The problem is that your element is designed to be exactly the width of its container - so setting `overflow: visible` on the container doesn't solve the problem (which it normally would) because the element isn't any larger than the container.

Here's my fix for your specific case:

1. Before you use `html2canvas` on your element `mod_pf_gantt_244`, set the width of its parent (in your case the `body` of the new window you create) to an arbitrarily large width, something bigger than your element could possibly be:
    ```js
    var el = document.getElementById('mod_pf_gantt_244');
    el.parentElement.style.width = '10000px';
    ```

2. Then, to prevent your element from filling the entire width we just set, change the element's `display` style to `inline-block` (and make sure `width` is set to `auto`):
    ```js
    el.style.display = 'inline-block';
    el.style.width = 'auto';
    ```

That should give your element the right width, so that when you convert to canvas it will display correctly.

**Comment by Romerski** [comment]
Thank you for your reply and your fix! I'll try as soon as I can and I'll give you a response.

Thanks again!!

2017-04-01 20:59 GMT+02:00 Erik Koopmans <notifications@github.com<mailto:notifications@github.com>>:

@Romerski<https://github.com/Romerski>, I've had a look. The problem is that your element is designed to be exactly the width of its container - so setting overflow: visible on the container doesn't solve the problem (which it normally would) because the element isn't any larger than the container.

Here's my fix for your specific case:

  1.  Before you use html2canvas on your element mod_pf_gantt_244, set the width of its parent (in your case the body of the new window you create) to an arbitrarily large width, something bigger than your element could possibly be:

var el = document.getElementById('mod_pf_gantt_244');
el.parentElement.style.width = '10000px';

  2.  Then, to prevent your element from filling the entire width we just set, change the element's display style to inline-block (and make sure width is set to auto):

el.style.display = 'inline-block';
el.style.width = 'auto';

That should give your element the right width, so that when you convert to canvas it will display correctly.

**Comment by Romerski** [comment]
I've just tried and is working like a charm! Thanks again, my problem is fixed now.

I owe you one!

2017-04-03 8:36 GMT+02:00 Yeray Romero <yerayrome@outlook.com<mailto:yerayrome@outlook.com>>:
Thank you for your reply and your fix! I'll try as soon as I can and I'll give you a response.

Thanks again!!

2017-04-01 20:59 GMT+02:00 Erik Koopmans <notifications@github.com<mailto:notifications@github.com>>:

@Romerski<https://github.com/Romerski>, I've had a look. The problem is that your element is designed to be exactly the width of its container - so setting overflow: visible on the container doesn't solve the problem (which it normally would) because the element isn't any larger than the container.

Here's my fix for your specific case:

  1.  Before you use html2canvas on your element mod_pf_gantt_244, set the width of its parent (in your case the body of the new window you create) to an arbitrarily large width, something bigger than your element could possibly be:

var el = document.getElementById('mod_pf_gantt_244');
el.parentElement.style.width = '10000px';

  2.  Then, to prevent your element from filling the entire width we just set, change the element's display style to inline-block (and make sure width is set to auto):

el.style.display = 'inline-block';
el.style.width = 'auto';

That should give your element the right width, so that when you convert to canvas it will display correctly.

**Comment by eKoopmans** [comment]
You're welcome @Romerski, glad it works!

**Comment by bruce1i** [comment]
@eKoopmans thanks, I need the feature and it works for me.

**Comment by PieterJanVdb** [comment]
@eKoopmans Any reason as to why this has not been reviewed / accepted yet?

**Comment by Darkmift** [comment]
Hi,

I am trying to apply a proper print but I am having an issue with the function when called by onclick.

Please see my demonstration:

https://www.youtube.com/watch?v=QrODj-bbv-Y&lc=z23xe15xjvfrgvvvbacdp433tbsjid5ifqxrnt4g5mdw03c010c.1504201255991820

link to project.
https://drive.google.com/drive/folders/0ByKwGLBGU4mPaVUwYVV1QlVQUUE

Any help would be deeply appreciated.

**Comment by eKoopmans** [comment]
@PieterJanVdb the repo owner is doing a big overhaul on html2canvas, I think the new build will have this issue (and many others) resolved. I'm also not sure my solution is perfect...

@Darkmift I've taken a look, and I have to admit I'm confused! I can tell you the different results you're getting are due to your scroll position - so where you say you have to restart the browser, that's not necessary, it's just where you're scrolled to on the screen. But regarding how to fix it... I'm still trying to figure it out!

**Comment by idolizesc** [comment]
Has this been fixed in the latest version?

**Comment by eKoopmans** [comment]
@idolizesc good question! In my testing... yes!! It's fixed!

As of v1.0.0-a1, I believe this issue is resolved, in both foreignObjectRendering and regular rendering. Thanks @niklasvh! I'll close this PR - if anyone has any continued problems with offscreen rendering, please post again here.

**Comment by OsipovDenis** [comment]
@eKoopmans hello!  Thank you for your work! But now, I got the same issue)
I'm upgraded html2canvas to the latest (1.0.0.-alpha.1) version, and it's broke my code.
When I used v.0.5.0 my "point" was in `opacity: 0;` at the container in which was my nodes for transform to canvas.
Now, I try to use anyone of solutions in this repo and it's don't help me.
Could you tell, please:
1) Which difference between 0.5.0 and 1.0.0?
2) Which base rules of rendering offscreen? (if i wanna create image and don't show it process to user?)

Now, it's working correctly if i create image from node on my screen and don't working if i positioned container relative with `left: 2000px;`

**Comment by ShrutiA11** [comment]
when data is too large html2canvas isnt printing the whole data it creates a space after printing certain amount of data else it will be blank page, 
would you pls help me on this

**Comment by Tholem98** [comment]
@ShrutiA11 I had the same problem. I fixed it passing the option scrollY:-window.scrollY
It solve my problem on desktop, but don't solve it on mobile

**Pull request closed without merging**
