### PR TITLE
fixing loading images in iframes when using foreignObject

### PR DESCRIPTION
**Pull request by jolan78**
probably necessary too for other elements inside iframes

### CODE REVIEW

**Comment by jolan78** [comment]
npm test returns no errors on my side using MacOS 10.11.6 and the same browser versions as travis

**Comment by niklasvh** [comment]
Do you have a test case where the issue can be replicated? Would like to make sure any fixes are not later broken again by adding tests for them.

**Comment by jolan78** [comment]
here is a simple test : 
[test.zip](https://github.com/niklasvh/html2canvas/files/1495566/test.zip)
it will not work for me if I simply open it with a browser due to cross-origin issues.

**Comment by niklasvh** [comment]
Interesting if the doctype actually affects the rendering, in that case the cloned document should actually use the same doctype.

**Comment by jolan78** [comment]
I will continue to discuss the doctype issue in https://github.com/niklasvh/html2canvas/issues/1298 . this pull request was about loading images in iframes, sorry for the confusion

**Pull request closed without merging**
